# Copyright © 2020, Octave Online LLC
#
# This file is part of Octave Online Server.
#
# Octave Online Server is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# Octave Online Server is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Octave Online Server.  If not, see
# <https://www.gnu.org/licenses/>.

##################################################################
# This is a docker-compose.yaml for a "quick start" installation #
##################################################################

#########################################################
# NOTE: All local paths are relative to repository root #
#########################################################

version: '3'
services:
  utils-gitd:
    image: octaveonline/utils-gitd:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/utils-gitd/Dockerfile
    ports:
      - "3003:3003"
      - "9418:9418"
    volumes:
      - git:/srv/oo/git
    read_only: true
    tmpfs:
      - /run
      - /tmp
  utils-gith:
    image: octaveonline/utils-gith:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/utils-gith/Dockerfile
    ports:
      - "3013:3013"
      - "3023:3023"
    volumes:
      - git:/srv/oo/git
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /run/php
      - /srv/oo/gitlist-oo/cache:uid=33
  oo-gith:
    image: octaveonline/oo-gith:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/oo-gith/Dockerfile
    ports:
      - "3033:80"
    depends_on:
      - mongod
    read_only: true
    tmpfs:
      - /run
      - /tmp
      - /run/oosocks
      - /var/log/nginx
      - /var/lib/nginx
  mongod:
    image: docker.io/library/mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db
    read_only: true
    # Log all commands. (TODO: consider the performance penalty?)
    command: --slowms=1
    tmpfs:
      - /run
      - /tmp
  redis:
    image: docker.io/library/redis:latest
    ports:
      - "6379:6379"
    read_only: true
    tmpfs:
      - /run
      - /tmp
  octave-deps:
    image: octaveonline/octave-deps:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/octave-deps/Dockerfile
    read_only: true
  octave-stable:
    image: octaveonline/octave-stable:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/octave-stable/Dockerfile
      args: ["FULL_BASE_IMAGE=octaveonline/octave-deps:v1.0.0"]
    depends_on: ["octave-deps"]
  octave-pkg:
    image: octaveonline/octave-pkg:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/octave-pkg/Dockerfile
      args: ["FULL_BASE_IMAGE=octaveonline/octave-stable:v1.0.0"]
    depends_on: ["octave-stable"]
  octave-oo:
    image: octaveonline/octave-oo:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/octave-oo/Dockerfile
      args: ["FULL_BASE_IMAGE=octaveonline/octave-pkg:v1.0.0"]
    depends_on: ["octave-pkg"]
  oo-back:
    image: octaveonline/oo-back:v1.0.0
    build:
      context: "../.."
      dockerfile: containers/oo-back/Dockerfile
      args: ["FULL_BASE_IMAGE=octaveonline/octave-oo:v1.0.0"]
    depends_on:
      - octave-oo
      - redis
      - mongod
    volumes:
      - logs:/srv/logs
    read_only: true
volumes:
  git:
  mongodb:
  logs:
