# Copyright © 2020, Octave Online LLC
#
# This file is part of Octave Online Server.
#
# Octave Online Server is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# Octave Online Server is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
# License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with Octave Online Server.  If not, see
# <https://www.gnu.org/licenses/>.

#########################################################
# NOTE: All local paths are relative to repository root #
#########################################################

steps:

# Pull additional data from GCP, including config.hjson.
# NOTE: You probably need to change this, depending on how you store your config.hjson.
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
    - -c
    - |
      # Download config file from private repo
      # Copy AppEngine files to the root directory
      # Delete client/app/node_modules since it doesn't point anywhere
      # Log the current commit info in the build log
      gcloud source repos clone oo-misc1 &&
      (cd oo-misc1 && git log -n1) &&
      cp oo-misc1/gcp_config.hjson config.hjson &&
      find oo-misc1/appengine/utils-admin -type f -exec cp {} . \; &&
      rm -f package-lock.json &&
      rm -f client/app/node_modules &&
      rm -rf oo-misc1;

# Deploy to AppEngine
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  timeout: 1800s
  args:
    - -c
    - |
      [[ $? == 0 ]] || exit $?;  # exit if failure

      gcloud app deploy;

timeout: 1800s
